// Generated by scripts/build_water_features.py; do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::water_features {

struct Point {
  int32_t lat_e7;
  int32_t lon_e7;
};

struct Polyline {
  uint32_t point_offset;
  uint16_t point_count;
  uint8_t kind;
};

constexpr size_t kPointCount = 1161;
constexpr size_t kPolylineCount = 387;

extern const Point kPoints[];
extern const Polyline kPolylines[];

}  // namespace data::water_features
